# Generated by Django 2.2.11 on 2020-03-23 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gs_shipping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingmethod',
            old_name='slug',
            new_name='code',
        ),
    ]
