# Generated by Django 2.2.11 on 2020-03-06 19:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20181115_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='address_type',
            field=models.IntegerField(choices=[(1, 'OFFICE'), (2, 'HOME')], default=2),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='alt_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Alternate Contact Number', max_length=128, verbose_name='Alternate Phone number'),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 3, 6, 19, 27, 50, 829945, tzinfo=utc), verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='email',
            field=models.EmailField(blank=True, help_text='Email Address', max_length=254, verbose_name='Email ID'),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='In case we need to call you about your order', max_length=128, verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='address_type',
            field=models.IntegerField(choices=[(1, 'OFFICE'), (2, 'HOME')], default=2),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='alt_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Alternate Contact Number', max_length=128, verbose_name='Alternate Phone number'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='email',
            field=models.EmailField(blank=True, help_text='Email Address', max_length=254, verbose_name='Email ID'),
        ),
    ]
