# Generated by Django 3.0.9 on 2020-08-11 20:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_surcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='address_type',
            field=models.CharField(choices=[('1', 'OFFICE'), ('2', 'HOME')], default='2', max_length=1),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='alt_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Alternate Contact Number', max_length=128, region=None, verbose_name='Alternate Phone number'),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 8, 11, 20, 26, 31, 891459, tzinfo=utc), verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='email',
            field=models.EmailField(blank=True, help_text='Email Address', max_length=254, verbose_name='Email ID'),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='In case we need to call you about your order', max_length=128, region=None, verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='address_type',
            field=models.CharField(choices=[('1', 'OFFICE'), ('2', 'HOME')], default='2', max_length=1),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='alt_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Alternate Contact Number', max_length=128, region=None, verbose_name='Alternate Phone number'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 8, 11, 20, 26, 38, 556715, tzinfo=utc), verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='email',
            field=models.EmailField(blank=True, help_text='Email Address', max_length=254, verbose_name='Email ID'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Created'),
        ),
    ]
