# Generated by Django 2.2.12 on 2020-04-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_auto_20200307_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address_type',
            field=models.CharField(choices=[('1', 'OFFICE'), ('2', 'HOME')], default='2', max_length=1),
        ),
    ]
