# Generated by Django 3.0.9 on 2020-08-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Shipping Method Name', max_length=255, verbose_name='Name')),
                ('charge_excl_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charge_incl_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('code', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Shipping Method',
                'verbose_name_plural': 'Shipping Methods',
            },
        ),
    ]
